spring:
  application:
    name: eureka-server
server:
  port: 8761
#---
#spring:
##  profiles: pro
#  boot:
#    admin:
#      client:
#        url: http://127.0.0.1:7086
#        instance:
#          prefer-ip: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always
#
#eureka:
#  server:
#    enable-self-preservation: true
#    eviction-interval-timer-in-ms: 3000
##  instance:
##    hostname: 127.0.0.1 #内网ip
##    lease-renewal-interval-in-seconds: 1
##    lease-expiration-duration-in-seconds: 3
##    prefer-ip-address: true
##    instance-id : 127.0.0.1:${spring.application.name}:${server.port}:0.0.1-SNAPSHOT
##    status-page-url: http://127.0.0.1:8761/swagger-ui.html
#  client:
#    register-with-eureka: false
#    fetchRegistry: false
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka
#---
##spring:
##  profiles: pro-sh
##  boot:
##    admin:
##      client:
##        url: http://127.0.0.1:7086
##eureka:
##  server:
##    enable-self-preservation: true
##    eviction-interval-timer-in-ms: 3000
##  instance:
##    hostname: 127.0.0.1
##    lease-renewal-interval-in-seconds: 1
##    lease-expiration-duration-in-seconds: 3
##    prefer-ip-address: true
##    instance-id : 172.16.19.6:${spring.application.name}:${server.port}:0.0.1-SNAPSHOT
##    status-page-url: http://127.0.0.1:8761/swagger-ui.html
##  client:
##    register-with-eureka: false
##    fetchRegistry: false
##    service-url:
##      defaultZone: http://127.0.0.1:8761/eureka
#
##  main:
##    allow-bean-definition-overriding: true