spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  # 修改在服务中心的地址status为 ip+端口 【例如：10.0.0.100:88】
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${eureka.instance.non-secure-port}
    #设置外网IP号
#    ip-address: 192.168.5.4
    #设置外网端口号
    non-secure-port: 8761
    ##踢出时间
    leaseRenewalIntervalInSeconds: 5
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://192.168.5.4:8761/eureka/
