server:
  port: 8888
#服务全局名称
spring:
  application:
    name: config-server
  cloud:
    config:
      discovery:
        enabled: true
    ##消息总线
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 192.168.5.4
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    publisher-confirms: true
##eureka配置
eureka:
  # 修改在服务中心的地址status为 ip+端口 【例如：10.0.0.100:88】
  instance:
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${eureka.instance.non-secure-port}
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    #设置外网IP号
    ip-address: 192.168.5.4
    #设置外网端口号
    non-secure-port: 8888
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://192.168.5.4:8761/eureka/
##构建信息
info:
  build:
    artifactId: @project.artifactId@
    version: @project.version@
    name: @project.name@
    groupId: @project.groupId@